$schema: "http://json-schema.org/draft-06/schema#"

description: MOSCA configuration file

type: object

version:
  type: string

output:
  type: string

resources_directory:
  type: string

threads:
  type: integer

experiments:
  type: array
  items:
    type: object
    properties:
      Files:
        type: string
      Sample:
        type: string
      "Data type":
        type: string
        enum: [dna, mrna, protein]
      Condition:
        type: string
      Name:
        type: string
    required: [Files, Sample, "Data type"]
  minItems: 1

minimum_read_length:
  type: integer

minimum_read_average_quality:
  type: integer

do_assembly:
  type: boolean

max_memory:
  type: float

assembler:
  type: string

error_model:
  type: string

markerset:
  type: string

do_binning:
  type: boolean

do_iterative_binning:
  type: boolean

upimapi_search_mode:
  type: string

upimapi_database:
  type: string

upimapi_max_target_seqs:
  type: integer

upimapi_taxids:
  type: string

upimapi_check_db:
  type: boolean

uniprot_columns:
  type: array

download_cdd_resources:
  type: boolean

recognizer_databases:
  type: array

normalization_method:
  type: string

minimum_differential_expression:
  type: number

metaproteomics_add_reference_proteomes:
  type: boolean

use_crap:
  type: boolean

proteomics_contaminants_database:
  type: string

reference_proteomes_taxa_level:
  type: string

protease:
  type: string

protease_file:
  type: string

false_discovery_rate:
  type: number

keggcharter_taxa_level:
  type: string

keggcharter_number_of_taxa:
  type: integer

keggcharter_maps:
  type: array

required:
  - output
  - resources_directory
  - threads
  - experiments
