name: base
channels:
  - conda-forge
  - bioconda
  - anaconda
  - defaults
dependencies:
  - bioconductor-deseq2
  - bioconductor-edger
  - bioconductor-rots
  - biopython
  - blast>=2.12
  - bowtie2
  - checkm-genome
  - fastqc
  - fraggenescan
  - gmcloser
  - keggcharter
  - krona=2.5
  - lxml
  - maxbin2
  - maxquant=2
  - megahit
  - metaphlan>=3
  - numpy
  - pandas
  - peptide-shaker=2
  - perl=5.26
  - python=3
  - quast
  - r-optparse
  - r-pheatmap
  - r-rcolorbrewer
  - recognizer>=1.8
  - requests
  - samtools
  - searchgui=4
  - seqkit
  - snakemake
  - snakemake-minimal
  - sortmerna=4
  - spades
  - subversion
  - trimmomatic
  - trinity
  - upimapi>=1.7
  - xlrd
  - xlsxwriter