name: mosca
channels:
  - r
  - conda-forge
  - bioconda
  - anaconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _r-mutex=1.0.1
  - aioeasywebdav=2.4.0
  - aiohttp=3.7.3
  - alsa-lib=1.2.3
  - amply=0.1.4
  - appdirs=1.4.4
  - apr=1.6.5
  - async-timeout=3.0.1
  - attmap=0.12.11
  - attrs=20.3.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.1
  - bcrypt=3.2.0
  - binutils_impl_linux-64=2.35.1
  - binutils_linux-64=2.35
  - bioconductor-affy=1.68.0
  - bioconductor-affyio=1.60.0
  - bioconductor-annotate=1.68.0
  - bioconductor-annotationdbi=1.52.0
  - bioconductor-biobase=2.50.0
  - bioconductor-biocgenerics=0.36.0
  - bioconductor-biocparallel=1.24.0
  - bioconductor-delayedarray=0.16.0
  - bioconductor-deseq2=1.30.0
  - bioconductor-edger=3.32.0
  - bioconductor-genefilter=1.72.0
  - bioconductor-geneplotter=1.68.0
  - bioconductor-genomeinfodb=1.26.0
  - bioconductor-genomeinfodbdata=1.2.4
  - bioconductor-genomicranges=1.42.0
  - bioconductor-iranges=2.24.0
  - bioconductor-limma=3.46.0
  - bioconductor-matrixgenerics=1.2.0
  - bioconductor-pcamethods=1.82.0
  - bioconductor-preprocesscore=1.52.0
  - bioconductor-rots=1.18.0
  - bioconductor-s4vectors=0.28.0
  - bioconductor-summarizedexperiment=1.20.0
  - bioconductor-vsn=3.58.0
  - bioconductor-xvector=0.30.0
  - bioconductor-zlibbioc=1.36.0
  - biopython=1.78
  - blast=2.10.1
  - boost-cpp=1.70.0
  - boto3=1.16.28
  - botocore=1.19.28
  - bowtie2=2.3.5.1
  - brotlipy=0.7.0
  - bwidget=1.9.14
  - bzip2=1.0.8
  - c-ares=1.17.1
  - ca-certificates=2020.12.5
  - cachetools=4.1.1
  - cairo=1.16.0
  - certifi=2020.12.5
  - cffi=1.14.4
  - chardet=3.0.4
  - checkm-genome=1.1.3
  - circos=0.69.8
  - coincbc=2.10.5
  - configargparse=1.2.3
  - cryptography=3.2.1
  - curl=7.71.1
  - cycler=0.10.0
  - cyrus-sasl=2.1.27
  - datrie=0.8.2
  - decorator=4.4.2
  - dendropy=4.5.1
  - diamond=2.0.5
  - docutils=0.16
  - dropbox=10.9.0
  - entrez-direct=13.9
  - et_xmlfile=1.0.1
  - expat=2.2.9
  - fastqc=0.11.9
  - fftw=3.3.8
  - filechunkio=1.8
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=2.001
  - font-ttf-source-code-pro=2.030
  - font-ttf-ubuntu=0.83
  - fontconfig=2.13.1
  - fonts-conda-forge=1
  - fraggenescan=1.31
  - freetype=2.10.4
  - fribidi=1.0.10
  - ftputil=4.0.0
  - gcc_impl_linux-64=7.5.0
  - gcc_linux-64=7.5.0
  - gdk-pixbuf=2.42.0
  - gettext=0.19.8.1
  - gfortran_impl_linux-64=7.5.0
  - gfortran_linux-64=7.5.0
  - ghostscript=9.53.3
  - giflib=5.2.1
  - gitdb=4.0.5
  - gitpython=3.1.11
  - glib=2.66.3
  - glimmerhmm=3.0.4
  - google-api-core=1.23.0
  - google-api-python-client=1.12.8
  - google-auth=1.23.0
  - google-auth-httplib2=0.0.4
  - google-cloud-core=1.4.3
  - google-cloud-storage=1.33.0
  - google-crc32c=1.0.0
  - google-resumable-media=1.1.0
  - googleapis-common-protos=1.52.0
  - graphite2=1.3.13
  - graphviz=2.42.3
  - grpcio=1.34.0
  - gsl=2.6
  - gxx_impl_linux-64=7.5.0
  - gxx_linux-64=7.5.0
  - harfbuzz=2.7.2
  - hmmer=3.3.1
  - htseq=0.12.4
  - htslib=1.11
  - httplib2=0.18.1
  - icu=67.1
  - idba=1.1.3
  - idna=2.10
  - imagemagick=7.0.10_28
  - importlib-metadata=3.1.1
  - importlib_metadata=3.1.1
  - iniconfig=1.1.1
  - ipython_genutils=0.2.0
  - jbig=2.1
  - jdcal=1.4.1
  - jinja2=2.11.2
  - jmespath=0.10.0
  - joblib=0.17.0
  - jpeg=9d
  - jsonschema=3.2.0
  - jupyter_core=4.7.0
  - k8=0.2.5
  - keggcharter=0.2.1
  - kernel-headers_linux-64=2.6.32
  - kiwisolver=1.3.1
  - krb5=1.17.2
  - krona=2.7.1
  - lcms2=2.11
  - ld_impl_linux-64=2.35.1
  - libapr=1.6.5
  - libapriconv=1.2.2
  - libaprutil=1.6.1
  - libblas=3.8.0
  - libcblas=3.8.0
  - libcrc32c=1.1.1
  - libcurl=7.71.1
  - libdeflate=1.6
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.3
  - libgcc=7.2.0
  - libgcc-ng=9.3.0
  - libgd=2.2.5
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libglib=2.66.3
  - libgomp=9.3.0
  - libiconv=1.16
  - libidn2=2.3.0
  - liblapack=3.8.0
  - libnghttp2=1.41.0
  - libntlm=1.4
  - libopenblas=0.3.10
  - libpng=1.6.37
  - libprotobuf=3.13.0.1
  - librsvg=2.50.2
  - libsodium=1.0.18
  - libssh2=1.9.0
  - libstdcxx-ng=9.3.0
  - libtiff=4.1.0
  - libtool=2.4.6
  - libunistring=0.9.10
  - libutf8proc=2.1.1
  - libuuid=2.32.1
  - libwebp=1.1.0
  - libwebp-base=1.1.0
  - libxcb=1.13
  - libxml2=2.9.10
  - libxslt=1.1.33
  - llvm-meta=7.0.0
  - logmuse=0.2.6
  - lxml=4.6.2
  - lz4-c=1.8.3
  - make=4.3
  - markupsafe=1.1.1
  - matplotlib-base=3.3.3
  - maxbin2=2.2.7
  - maxquant=1.6.10.43
  - megahit=1.2.9
  - minimap2=2.17
  - mono=5.14.0.177
  - more-itertools=8.6.0
  - mosca=1.2.1
  - multidict=4.7.5
  - nbformat=5.0.8
  - ncurses=6.2
  - networkx=2.5
  - numpy=1.19.4
  - oauth2client=4.1.3
  - olefile=0.46
  - openjdk=11.0.8
  - openjpeg=2.3.1
  - openmp=7.0.0
  - openpyxl=3.0.5
  - openssl=1.1.1j
  - packaging=20.8
  - pandas=1.1.4
  - pango=1.42.4
  - paramiko=2.7.2
  - pcre=8.44
  - pcre2=10.35
  - pear=0.9.6
  - peppy=0.31.0
  - perl=5.26.2
  - perl-app-cpanminus=1.7044
  - perl-archive-tar=2.32
  - perl-autoloader=5.74
  - perl-base=2.23
  - perl-business-isbn=3.004
  - perl-business-isbn-data=20140910.003
  - perl-carp=1.38
  - perl-clone=0.42
  - perl-common-sense=3.74
  - perl-compress-raw-bzip2=2.087
  - perl-compress-raw-zlib=2.087
  - perl-config-general=2.63
  - perl-constant=1.33
  - perl-data-dumper=2.173
  - perl-digest-hmac=1.03
  - perl-digest-md5=2.55
  - perl-digest-perl-md5=1.9
  - perl-dynaloader=1.25
  - perl-encode=2.88
  - perl-encode-locale=1.05
  - perl-exporter=5.72
  - perl-exporter-tiny=1.002001
  - perl-extutils-makemaker=7.36
  - perl-file-listing=6.04
  - perl-file-path=2.16
  - perl-file-temp=0.2304
  - perl-font-ttf=1.06
  - perl-gd=2.71
  - perl-html-parser=3.72
  - perl-html-tagset=3.20
  - perl-html-tree=5.07
  - perl-http-cookies=6.04
  - perl-http-daemon=6.01
  - perl-http-date=6.02
  - perl-http-message=6.18
  - perl-http-negotiate=6.01
  - perl-io-compress=2.087
  - perl-io-html=1.001
  - perl-io-socket-ssl=2.066
  - perl-io-string=1.08
  - perl-io-zlib=1.10
  - perl-json=4.02
  - perl-json-xs=2.34
  - perl-libwww-perl=6.39
  - perl-list-moreutils=0.428
  - perl-list-moreutils-xs=0.428
  - perl-lwp-mediatypes=6.04
  - perl-lwp-protocol-https=6.07
  - perl-lwp-simple=6.15
  - perl-math-bezier=0.01
  - perl-math-round=0.07
  - perl-math-vecstat=0.08
  - perl-mime-base64=3.15
  - perl-module-implementation=0.09
  - perl-module-runtime=0.016
  - perl-mozilla-ca=20180117
  - perl-net-http=6.19
  - perl-net-ssleay=1.88
  - perl-ntlm=1.09
  - perl-number-format=1.75
  - perl-params-validate=1.29
  - perl-parent=0.236
  - perl-pathtools=3.75
  - perl-readonly=2.05
  - perl-regexp-common=2017060201
  - perl-scalar-list-utils=1.52
  - perl-set-intspan=1.19
  - perl-socket=2.027
  - perl-statistics-basic=1.6611
  - perl-storable=3.15
  - perl-svg=2.84
  - perl-test-requiresinternet=0.05
  - perl-text-format=0.59
  - perl-time-hires=1.9760
  - perl-time-local=1.28
  - perl-try-tiny=0.30
  - perl-types-serialiser=1.0
  - perl-uri=1.76
  - perl-www-robotrules=6.02
  - perl-xml-namespacesupport=1.12
  - perl-xml-parser=2.44_01
  - perl-xml-sax=1.02
  - perl-xml-sax-base=1.09
  - perl-xml-sax-expat=0.51
  - perl-xml-simple=2.25
  - perl-xsloader=0.24
  - pillow=8.0.1
  - pip=20.3.1
  - pixman=0.40.0
  - pkg-config=0.29.2
  - pluggy=0.13.1
  - pplacer=1.1.alpha19
  - prettytable=2.0.0
  - prodigal=2.6.3
  - progressbar=2.5
  - progressbar33=2.4
  - protobuf=3.13.0.1
  - psutil=5.7.3
  - pthread-stubs=0.4
  - pulp=2.3.1
  - py=1.10.0
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycparser=2.20
  - pygments=2.7.2
  - pygraphviz=1.6
  - pynacl=1.4.0
  - pyopenssl=20.0.0
  - pyparsing=2.4.7
  - pyrsistent=0.17.3
  - pysam=0.16.0.1
  - pysftp=0.2.9
  - pysocks=1.7.1
  - pytest=6.2.2
  - python=3.7.8
  - python-dateutil=2.8.1
  - python-irodsclient=0.8.2
  - python_abi=3.7
  - pytz=2020.4
  - pyyaml=5.3.1
  - quast=5.0.2
  - r-askpass=1.1
  - r-assertthat=0.2.1
  - r-backports=1.2.0
  - r-base=4.0.3
  - r-bh=1.72.0_3
  - r-biocmanager=1.30.10
  - r-bit=4.0.4
  - r-bit64=4.0.5
  - r-bitops=1.0_6
  - r-blob=1.2.1
  - r-brio=1.1.0
  - r-callr=3.5.1
  - r-catools=1.18.0
  - r-cli=2.2.0
  - r-colorspace=2.0_0
  - r-crayon=1.3.4
  - r-curl=4.3
  - r-dbi=1.1.0
  - r-desc=1.2.0
  - r-diffobj=0.3.2
  - r-digest=0.6.27
  - r-ellipsis=0.3.1
  - r-evaluate=0.14
  - r-fansi=0.4.1
  - r-farver=2.0.3
  - r-formatr=1.7
  - r-futile.logger=1.4.3
  - r-futile.options=1.0.1
  - r-getopt=1.20.3
  - r-ggplot2=3.3.2
  - r-glue=1.4.2
  - r-gplots=3.1.1
  - r-gtable=0.3.0
  - r-gtools=3.8.2
  - r-httr=1.4.2
  - r-isoband=0.2.3
  - r-jsonlite=1.7.1
  - r-kernsmooth=2.23_18
  - r-labeling=0.4.2
  - r-lambda.r=1.2.4
  - r-lattice=0.20_41
  - r-lifecycle=0.2.0
  - r-locfit=1.5_9.4
  - r-magrittr=2.0.1
  - r-mass=7.3_53
  - r-matrix=1.2_18
  - r-matrixstats=0.57.0
  - r-memoise=1.1.0
  - r-mgcv=1.8_33
  - r-mime=0.9
  - r-munsell=0.5.0
  - r-nlme=3.1_150
  - r-openssl=1.4.3
  - r-optparse=1.6.6
  - r-pheatmap=1.0.12
  - r-pillar=1.4.7
  - r-pkgbuild=1.1.0
  - r-pkgconfig=2.0.3
  - r-pkgload=1.1.0
  - r-plogr=0.2.0
  - r-praise=1.0.0
  - r-prettyunits=1.1.1
  - r-processx=3.4.5
  - r-ps=1.4.0
  - r-r6=2.5.0
  - r-rcolorbrewer=1.1_2
  - r-rcpp=1.0.5
  - r-rcpparmadillo=0.10.1.2.0
  - r-rcurl=1.98_1.2
  - r-rematch2=2.1.2
  - r-rlang=0.4.9
  - r-rprojroot=2.0.2
  - r-rsqlite=2.2.1
  - r-rstudioapi=0.13
  - r-scales=1.1.1
  - r-snow=0.4_3
  - r-survival=3.2_7
  - r-sys=3.4
  - r-testthat=3.0.0
  - r-tibble=3.0.4
  - r-utf8=1.1.4
  - r-vctrs=0.3.5
  - r-viridislite=0.3.0
  - r-waldo=0.2.3
  - r-withr=2.3.0
  - r-xml=3.99_0.3
  - r-xtable=1.8_4
  - r-zeallot=0.1.0
  - ratelimiter=1.2.0
  - readline=8.0
  - recognizer=1.4.1
  - reportlab=3.5.56
  - requests=2.25.0
  - rsa=4.6
  - s3transfer=0.3.3
  - samtools=1.11
  - scikit-learn=0.23.2
  - scipy=1.5.3
  - sed=4.8
  - seqkit=0.14.0
  - seqtk=1.3
  - serf=1.3.9
  - setuptools=49.6.0
  - simplejson=3.17.2
  - six=1.15.0
  - slacker=0.14.0
  - smmap=3.0.4
  - snakemake=5.32.0
  - snakemake-minimal=5.32.0
  - sortmerna=2.1b
  - spades=3.14.1
  - sqlite=3.34.0
  - svn=1.10.2
  - sysroot_linux-64=2.12
  - tar=1.32
  - tbb=2020.2
  - threadpoolctl=2.1.0
  - tk=8.6.10
  - tktable=2.10
  - toml=0.10.2
  - toposort=1.5
  - tornado=6.1
  - tqdm=4.54.0
  - traitlets=5.0.5
  - trimmomatic=0.39
  - typing-extensions=3.7.4.3
  - typing_extensions=3.7.4.3
  - ubiquerg=0.6.1
  - upimapi=1.1.2
  - uritemplate=3.0.1
  - urllib3=1.25.11
  - veracitools=0.1.3
  - wcwidth=0.2.5
  - wget=1.20.1
  - wheel=0.36.0
  - wrapt=1.12.1
  - xlrd=1.2.0
  - xlsxwriter=1.3.7
  - xmlrunner=1.7.7
  - xorg-fixesproto=5.0
  - xorg-inputproto=2.3.2
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.6.12
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxfixes=5.0.3
  - xorg-libxi=1.7.10
  - xorg-libxpm=3.5.13
  - xorg-libxrender=0.9.10
  - xorg-libxt=1.1.5
  - xorg-libxtst=1.2.3
  - xorg-recordproto=1.14.2
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.5
  - yaml=0.2.5
  - yarl=1.5.1
  - zipp=3.4.0
  - zlib=1.2.11
  - zstd=1.4.4
