name: mosca
channels:
  - conda-forge
  - bioconda
  - anaconda
  - defaults
dependencies:
  - conda-forge:_libgcc_mutex=0.1
  - conda-forge:_openmp_mutex=4.5
  - conda-forge:_r-mutex=1.0.1
  - _sysroot_linux-64_curr_repodata_hack=3
  - conda-forge:aioeasywebdav=2.4.0
  - aiohttp=3.7.4
  - conda-forge:alsa-lib=1.2.3
  - conda-forge:amply=0.1.4
  - conda-forge:appdirs=1.4.4
  - conda-forge:apr=1.7.0
  - anaconda:async-timeout=3.0.1
  - conda-forge:atk-1.0=2.36.0
  - conda-forge:attmap=0.13.0
  - attrs=20.3.0
  - anaconda:backports=1.0
  - backports.functools_lru_cache=1.6.1
  - bioconda:bcbio-gff=0.6.6
  - conda-forge:bcrypt=3.2.0
  - conda-forge:binutils_impl_linux-64=2.35.1
  - conda-forge:binutils_linux-64=2.35
  - bioconda:bioconductor-affy=1.68.0
  - bioconda:bioconductor-affyio=1.60.0
  - bioconda:bioconductor-annotate=1.68.0
  - bioconda:bioconductor-annotationdbi=1.52.0
  - bioconda:bioconductor-biobase=2.50.0
  - bioconda:bioconductor-biocgenerics=0.36.0
  - bioconda:bioconductor-biocparallel=1.24.0
  - bioconda:bioconductor-delayedarray=0.16.0
  - bioconda:bioconductor-deseq2=1.30.0
  - bioconda:bioconductor-edger=3.32.0
  - bioconda:bioconductor-genefilter=1.72.0
  - bioconda:bioconductor-geneplotter=1.68.0
  - bioconda:bioconductor-genomeinfodb=1.26.0
  - bioconda:bioconductor-genomeinfodbdata=1.2.4
  - bioconda:bioconductor-genomicranges=1.42.0
  - bioconda:bioconductor-iranges=2.24.0
  - bioconda:bioconductor-limma=3.46.0
  - bioconda:bioconductor-matrixgenerics=1.2.0
  - bioconda:bioconductor-pcamethods=1.82.0
  - bioconda:bioconductor-preprocesscore=1.52.0
  - bioconda:bioconductor-rots=1.18.0
  - bioconda:bioconductor-s4vectors=0.28.0
  - bioconda:bioconductor-summarizedexperiment=1.20.0
  - bioconda:bioconductor-vsn=3.58.0
  - bioconda:bioconductor-xvector=0.30.0
  - bioconda:bioconductor-zlibbioc=1.36.0
  - conda-forge:biom-format=2.1.10
  - conda-forge:biopython=1.78
  - conda-forge:blas=1.1
  - bioconda:blast=2.11.0
  - conda-forge:boost-cpp=1.70.0
  - anaconda:boto=2.49.0
  - conda-forge:boto3=1.17.30
  - conda-forge:botocore=1.20.30
  - bioconda:bowtie2=2.4.2
  - brotlipy=0.7.0
  - conda-forge:bwidget=1.9.14
  - bioconda:bx-python=0.8.11
  - anaconda:bz2file=0.98
  - conda-forge:bzip2=1.0.8
  - conda-forge:c-ares=1.17.1
  - ca-certificates=2021.1.19
  - conda-forge:cached-property=1.5.2
  - conda-forge:cached_property=1.5.2
  - conda-forge:cachetools=4.2.1
  - conda-forge:cairo=1.16.0
  - conda-forge:capnproto=0.6.1
  - conda-forge:certifi=2020.12.5
  - conda-forge:cffi=1.14.5
  - conda-forge:chardet=3.0.4
  - bioconda:checkm-genome=1.1.3
  - bioconda:circos=0.69.8
  - click=7.1.2
  - bioconda:cmseq=1.0.2
  - conda-forge:coincbc=2.10.5
  - conda-forge:configargparse=1.4
  - cryptography=3.4.6
  - conda-forge:curl=7.75.0
  - anaconda:cycler=0.10.0
  - conda-forge:cyrus-sasl=2.1.27
  - conda-forge:datrie=0.8.2
  - decorator=4.4.2
  - bioconda:dendropy=4.5.2
  - bioconda:diamond=2.0.8
  - conda-forge:docutils=0.16
  - dropbox=10.10.0
  - bioconda:entrez-direct=13.9
  - anaconda:et_xmlfile=1.0.1
  - anaconda:expat=2.2.10
  - bioconda:fastqc=0.11.9
  - bioconda:fasttree=2.1.10
  - fftw=3.3.9
  - conda-forge:filechunkio=1.8
  - filelock=3.0.12
  - conda-forge:font-ttf-dejavu-sans-mono=2.37
  - anaconda:font-ttf-inconsolata=2.001
  - conda-forge:font-ttf-source-code-pro=2.030
  - conda-forge:font-ttf-ubuntu=0.83
  - conda-forge:fontconfig=2.13.1
  - conda-forge:fonts-conda-ecosystem=1
  - conda-forge:fonts-conda-forge=1
  - bioconda:fraggenescan=1.31
  - conda-forge:freetype=2.10.4
  - conda-forge:fribidi=1.0.10
  - conda-forge:ftputil=5.0.0
  - conda-forge:future=0.18.2
  - conda-forge:gcc_impl_linux-64=9.3.0
  - conda-forge:gcc_linux-64=9.3.0
  - conda-forge:gdk-pixbuf=2.42.2
  - conda-forge:gettext=0.19.8.1
  - anaconda:gfortran_linux-64=7.2.0
  - conda-forge:ghostscript=9.53.3
  - conda-forge:giflib=5.2.1
  - conda-forge:gitdb=4.0.5
  - gitpython=3.1.14
  - conda-forge:glib=2.66.7
  - conda-forge:glib-tools=2.66.7
  - bioconda:glimmerhmm=3.0.4
  - conda-forge:google-api-core=1.25.1
  - conda-forge:google-api-python-client=2.0.2
  - google-auth=1.27.1
  - conda-forge:google-auth-httplib2=0.0.4
  - google-cloud-core=1.6.0
  - google-cloud-storage=1.36.2
  - conda-forge:google-crc32c=1.1.2
  - google-resumable-media=1.2.0
  - conda-forge:googleapis-common-protos=1.52.0
  - anaconda:graphite2=1.3.14
  - conda-forge:graphviz=2.47.0
  - conda-forge:gsl=2.6
  - conda-forge:gtk2=2.24.33
  - conda-forge:gts=0.7.6
  - conda-forge:gxx_impl_linux-64=9.3.0
  - conda-forge:gxx_linux-64=9.3.0
  - conda-forge:h5py=3.1.0
  - conda-forge:harfbuzz=2.7.2
  - conda-forge:hdf5=1.10.6
  - bioconda:hmmer=3.3.2
  - bioconda:htseq=0.13.5
  - bioconda:htslib=1.12
  - conda-forge:httplib2=0.19.0
  - conda-forge:icu=67.1
  - bioconda:idba=1.1.3
  - idna=2.10
  - conda-forge:imagemagick=7.0.10_28
  - importlib-metadata=3.7.3
  - importlib_metadata=3.7.3
  - iniconfig=1.1.1
  - anaconda:ipython_genutils=0.2.0
  - bioconda:iqtree=2.0.3
  - conda-forge:jbig=2.1
  - conda-forge:jdcal=1.4.1
  - jinja2=2.11.3
  - conda-forge:jmespath=0.10.0
  - conda-forge:joblib=1.0.1
  - conda-forge:jpeg=9d
  - anaconda:jsonschema=3.2.0
  - conda-forge:jupyter_core=4.7.1
  - bioconda:k8=0.2.5
  - bioconda:keggcharter=0.2.3
  - conda-forge:kernel-headers_linux-64=3.10.0
  - conda-forge:kiwisolver=1.3.1
  - conda-forge:krb5=1.17.2
  - bioconda:krona=2.8
  - conda-forge:lcms2=2.11
  - conda-forge:ld_impl_linux-64=2.35.1
  - conda-forge:libapr=1.7.0
  - conda-forge:libapriconv=1.2.2
  - conda-forge:libaprutil=1.6.1
  - conda-forge:libblas=3.8.0
  - conda-forge:libcblas=3.8.0
  - anaconda:libcrc32c=1.1.1
  - conda-forge:libcurl=7.75.0
  - libdeflate=1.7
  - libedit=3.1.20210216
  - conda-forge:libev=4.33
  - anaconda:libffi=3.3
  - conda-forge:libgcc=7.2.0
  - conda-forge:libgcc-devel_linux-64=9.3.0
  - conda-forge:libgcc-ng=9.3.0
  - conda-forge:libgd=2.3.0
  - conda-forge:libgfortran-ng=7.5.0
  - conda-forge:libgfortran4=7.5.0
  - conda-forge:libglib=2.66.7
  - conda-forge:libgomp=9.3.0
  - conda-forge:libiconv=1.16
  - conda-forge:libidn2=2.3.0
  - conda-forge:liblapack=3.8.0
  - conda-forge:libnghttp2=1.43.0
  - anaconda:libntlm=1.5
  - conda-forge:libopenblas=0.3.10
  - conda-forge:libpng=1.6.37
  - conda-forge:libprotobuf=3.15.6
  - conda-forge:librsvg=2.50.3
  - conda-forge:libsodium=1.0.18
  - conda-forge:libssh2=1.9.0
  - conda-forge:libstdcxx-devel_linux-64=9.3.0
  - conda-forge:libstdcxx-ng=9.3.0
  - conda-forge:libtiff=4.1.0
  - conda-forge:libtool=2.4.6
  - conda-forge:libunistring=0.9.10
  - anaconda:libutf8proc=2.1.1
  - conda-forge:libuuid=2.32.1
  - conda-forge:libwebp=1.1.0
  - conda-forge:libwebp-base=1.1.0
  - anaconda:libxcb=1.14
  - conda-forge:libxml2=2.9.10
  - conda-forge:libxslt=1.1.33
  - conda-forge:llvm-openmp=8.0.1
  - conda-forge:logmuse=0.2.6
  - conda-forge:lxml=4.6.2
  - conda-forge:lz4-c=1.8.3
  - conda-forge:lzo=2.10
  - bioconda:mafft=7.475
  - conda-forge:make=4.3
  - conda-forge:markupsafe=1.1.1
  - bioconda:mash=2.3
  - matplotlib-base=3.3.4
  - bioconda:maxbin2=2.2.7
  - bioconda:maxquant=1.6.10.43
  - bioconda:megahit=1.2.9
  - bioconda:metaphlan=3.0.7
  - bioconda:minimap2=2.17
  - conda-forge:mono=6.12.0.90
  - conda-forge:more-itertools=8.7.0
  - multidict=5.1.0
  - bioconda:muscle=3.8.1551
  - conda-forge:nbformat=5.1.2
  - conda-forge:ncurses=6.2
  - conda-forge:networkx=2.5
  - conda-forge:numpy=1.20.1
  - conda-forge:oauth2client=4.1.3
  - anaconda:olefile=0.46
  - conda-forge:openblas=0.3.10
  - conda-forge:openjdk=11.0.8
  - conda-forge:openjpeg=2.4.0
  - conda-forge:openmp=8.0.1
  - conda-forge:openpyxl=3.0.7
  - openssl=1.1.1j
  - packaging=20.9
  - conda-forge:pandas=1.2.3
  - conda-forge:pango=1.42.4
  - conda-forge:paramiko=2.7.2
  - anaconda:patsy=0.5.1
  - anaconda:pcre=8.44
  - conda-forge:pcre2=10.35
  - conda-forge:peppy=0.31.0
  - bioconda:peptide-shaker=1.16.40
  - conda-forge:perl=5.26.2
  - bioconda:perl-app-cpanminus=1.7044
  - bioconda:perl-archive-tar=2.32
  - bioconda:perl-autoloader=5.74
  - bioconda:perl-base=2.23
  - bioconda:perl-business-isbn=3.004
  - bioconda:perl-business-isbn-data=20140910.003
  - bioconda:perl-carp=1.38
  - bioconda:perl-clone=0.42
  - bioconda:perl-common-sense=3.74
  - bioconda:perl-compress-raw-bzip2=2.087
  - bioconda:perl-compress-raw-zlib=2.087
  - bioconda:perl-config-general=2.63
  - bioconda:perl-constant=1.33
  - bioconda:perl-data-dumper=2.173
  - bioconda:perl-digest-hmac=1.03
  - bioconda:perl-digest-md5=2.55
  - bioconda:perl-digest-perl-md5=1.9
  - bioconda:perl-dynaloader=1.25
  - bioconda:perl-encode=2.88
  - bioconda:perl-encode-locale=1.05
  - bioconda:perl-exporter=5.72
  - bioconda:perl-exporter-tiny=1.002001
  - bioconda:perl-extutils-makemaker=7.36
  - bioconda:perl-file-listing=6.04
  - bioconda:perl-file-path=2.16
  - bioconda:perl-file-temp=0.2304
  - bioconda:perl-font-ttf=1.06
  - bioconda:perl-gd=2.68
  - bioconda:perl-html-parser=3.72
  - bioconda:perl-html-tagset=3.20
  - bioconda:perl-html-tree=5.07
  - bioconda:perl-http-cookies=6.04
  - bioconda:perl-http-daemon=6.01
  - bioconda:perl-http-date=6.02
  - bioconda:perl-http-message=6.18
  - bioconda:perl-http-negotiate=6.01
  - bioconda:perl-io-compress=2.087
  - bioconda:perl-io-html=1.001
  - bioconda:perl-io-socket-ssl=2.066
  - bioconda:perl-io-string=1.08
  - bioconda:perl-io-zlib=1.10
  - bioconda:perl-json=4.02
  - bioconda:perl-json-xs=2.34
  - bioconda:perl-libwww-perl=6.39
  - bioconda:perl-list-moreutils=0.428
  - bioconda:perl-list-moreutils-xs=0.428
  - bioconda:perl-lwp-mediatypes=6.04
  - bioconda:perl-lwp-protocol-https=6.07
  - bioconda:perl-lwp-simple=6.15
  - bioconda:perl-math-bezier=0.01
  - bioconda:perl-math-round=0.07
  - bioconda:perl-math-vecstat=0.08
  - bioconda:perl-mime-base64=3.15
  - bioconda:perl-module-implementation=0.09
  - bioconda:perl-module-runtime=0.016
  - bioconda:perl-mozilla-ca=20180117
  - bioconda:perl-net-http=6.19
  - bioconda:perl-net-ssleay=1.88
  - bioconda:perl-ntlm=1.09
  - bioconda:perl-number-format=1.75
  - bioconda:perl-params-validate=1.29
  - bioconda:perl-parent=0.236
  - bioconda:perl-pathtools=3.75
  - bioconda:perl-readonly=2.05
  - bioconda:perl-regexp-common=2017060201
  - bioconda:perl-scalar-list-utils=1.52
  - bioconda:perl-set-intspan=1.19
  - bioconda:perl-socket=2.027
  - bioconda:perl-statistics-basic=1.6611
  - bioconda:perl-storable=3.15
  - bioconda:perl-svg=2.84
  - bioconda:perl-test-requiresinternet=0.05
  - bioconda:perl-text-format=0.59
  - bioconda:perl-time-hires=1.9760
  - bioconda:perl-time-local=1.28
  - bioconda:perl-try-tiny=0.30
  - bioconda:perl-types-serialiser=1.0
  - bioconda:perl-uri=1.76
  - bioconda:perl-www-robotrules=6.02
  - bioconda:perl-xml-namespacesupport=1.12
  - conda-forge:perl-xml-parser=2.44_01
  - bioconda:perl-xml-sax=1.02
  - bioconda:perl-xml-sax-base=1.09
  - bioconda:perl-xml-sax-expat=0.51
  - bioconda:perl-xml-simple=2.25
  - bioconda:perl-xsloader=0.24
  - bioconda:phylophlan=3.0.2
  - pillow=8.1.2
  - pip=21.0.1
  - conda-forge:pixman=0.38.0
  - conda-forge:pkg-config=0.29.2
  - conda-forge:pluggy=0.13.1
  - bioconda:pplacer=1.1.alpha19
  - conda-forge:prettytable=2.1.0
  - bioconda:prodigal=2.6.3
  - conda-forge:progressbar=2.5
  - conda-forge:progressbar33=2.4
  - conda-forge:protobuf=3.15.6
  - psutil=5.8.0
  - conda-forge:pulp=2.4
  - py=1.10.0
  - conda-forge:pyasn1=0.4.8
  - anaconda:pyasn1-modules=0.2.8
  - conda-forge:pycparser=2.20
  - conda-forge:pygments=2.8.1
  - conda-forge:pygraphviz=1.7
  - conda-forge:pynacl=1.4.0
  - pyopenssl=20.0.1
  - pyparsing=2.4.7
  - conda-forge:pyrsistent=0.17.3
  - bioconda:pysam=0.16.0.1
  - conda-forge:pysftp=0.2.9
  - conda-forge:pysocks=1.7.1
  - pytest=6.2.2
  - conda-forge:python=3.7.10
  - python-dateutil=2.8.1
  - conda-forge:python-irodsclient=0.8.6
  - conda-forge:python-lzo=1.12
  - conda-forge:python_abi=3.7
  - conda-forge:pytz=2021.1
  - pyyaml=5.4.1
  - bioconda:quast=5.0.2
  - conda-forge:r-askpass=1.1
  - conda-forge:r-assertthat=0.2.1
  - conda-forge:r-backports=1.2.1
  - conda-forge:r-base=4.0.2
  - conda-forge:r-bh=1.75.0_0
  - conda-forge:r-biocmanager=1.30.10
  - conda-forge:r-bit=4.0.4
  - conda-forge:r-bit64=4.0.5
  - conda-forge:r-bitops=1.0_6
  - conda-forge:r-blob=1.2.1
  - conda-forge:r-brio=1.1.1
  - conda-forge:r-cachem=1.0.4
  - conda-forge:r-callr=3.5.1
  - conda-forge:r-catools=1.18.1
  - conda-forge:r-cli=2.3.1
  - conda-forge:r-colorspace=2.0_0
  - conda-forge:r-crayon=1.4.1
  - conda-forge:r-curl=4.3
  - conda-forge:r-dbi=1.1.1
  - conda-forge:r-desc=1.3.0
  - conda-forge:r-diffobj=0.3.3
  - conda-forge:r-digest=0.6.27
  - conda-forge:r-ellipsis=0.3.1
  - conda-forge:r-evaluate=0.14
  - conda-forge:r-fansi=0.4.2
  - conda-forge:r-farver=2.1.0
  - conda-forge:r-fastmap=1.1.0
  - conda-forge:r-formatr=1.8
  - conda-forge:r-futile.logger=1.4.3
  - conda-forge:r-futile.options=1.0.1
  - conda-forge:r-getopt=1.20.3
  - conda-forge:r-ggplot2=3.3.3
  - conda-forge:r-glue=1.4.2
  - conda-forge:r-gplots=3.1.1
  - conda-forge:r-gtable=0.3.0
  - conda-forge:r-gtools=3.8.2
  - conda-forge:r-httr=1.4.2
  - conda-forge:r-isoband=0.2.4
  - conda-forge:r-jsonlite=1.7.2
  - conda-forge:r-kernsmooth=2.23_18
  - conda-forge:r-labeling=0.4.2
  - conda-forge:r-lambda.r=1.2.4
  - conda-forge:r-lattice=0.20_41
  - conda-forge:r-lifecycle=1.0.0
  - conda-forge:r-locfit=1.5_9.4
  - conda-forge:r-magrittr=2.0.1
  - conda-forge:r-mass=7.3_53.1
  - conda-forge:r-matrix=1.3_2
  - conda-forge:r-matrixstats=0.58.0
  - conda-forge:r-memoise=2.0.0
  - conda-forge:r-mgcv=1.8_34
  - conda-forge:r-mime=0.10
  - conda-forge:r-munsell=0.5.0
  - conda-forge:r-nlme=3.1_150
  - conda-forge:r-openssl=1.4.3
  - conda-forge:r-optparse=1.6.6
  - conda-forge:r-pheatmap=1.0.12
  - conda-forge:r-pillar=1.5.1
  - conda-forge:r-pkgbuild=1.2.0
  - conda-forge:r-pkgconfig=2.0.3
  - conda-forge:r-pkgload=1.2.0
  - conda-forge:r-plogr=0.2.0
  - conda-forge:r-praise=1.0.0
  - conda-forge:r-prettyunits=1.1.1
  - conda-forge:r-processx=3.4.5
  - conda-forge:r-ps=1.6.0
  - conda-forge:r-r6=2.5.0
  - conda-forge:r-rcolorbrewer=1.1_2
  - conda-forge:r-rcpp=1.0.6
  - conda-forge:r-rcpparmadillo=0.10.2.2.0
  - conda-forge:r-rcurl=1.98_1.3
  - conda-forge:r-rematch2=2.1.2
  - conda-forge:r-rlang=0.4.10
  - conda-forge:r-rprojroot=2.0.2
  - conda-forge:r-rsqlite=2.2.4
  - conda-forge:r-rstudioapi=0.13
  - conda-forge:r-scales=1.1.1
  - conda-forge:r-snow=0.4_3
  - conda-forge:r-survival=3.2_10
  - conda-forge:r-sys=3.4
  - conda-forge:r-testthat=3.0.2
  - conda-forge:r-tibble=3.1.0
  - conda-forge:r-utf8=1.2.1
  - conda-forge:r-vctrs=0.3.6
  - conda-forge:r-viridislite=0.3.0
  - conda-forge:r-waldo=0.2.5
  - conda-forge:r-withr=2.4.1
  - conda-forge:r-xml=3.99_0.6
  - conda-forge:r-xtable=1.8_4
  - conda-forge:r-zeallot=0.1.0
  - conda-forge:ratelimiter=1.2.0
  - bioconda:raxml=8.2.12
  - readline=8.1
  - bioconda:recognizer=1.4.3
  - reportlab=3.5.65
  - requests=2.25.1
  - rsa=4.7.2
  - conda-forge:s3transfer=0.3.4
  - bioconda:samtools=1.12
  - scikit-learn=0.24.1
  - scipy=1.6.1
  - conda-forge:seaborn=0.11.1
  - conda-forge:seaborn-base=0.11.1
  - bioconda:searchgui=3.3.10
  - conda-forge:sed=4.8
  - bioconda:seqkit=0.15.0
  - bioconda:seqtk=1.3
  - conda-forge:serf=1.3.9
  - setuptools=52.0.0
  - simplejson=3.17.2
  - six=1.15.0
  - conda-forge:slacker=0.14.0
  - conda-forge:smart_open=4.2.0
  - smmap=3.0.5
  - bioconda:snakemake=6.0.5
  - bioconda:snakemake-minimal=6.0.5
  - bioconda:sortmerna=2.1b
  - bioconda:spades=3.15.2
  - sqlite=3.35.1
  - conda-forge:statsmodels=0.12.2
  - anaconda:svn=1.10.2
  - conda-forge:sysroot_linux-64=2.17
  - conda-forge:tar=1.34
  - conda-forge:tbb=2020.2
  - conda-forge:threadpoolctl=2.1.0
  - conda-forge:tk=8.6.10
  - conda-forge:tktable=2.10
  - conda-forge:toml=0.10.2
  - conda-forge:toposort=1.6
  - conda-forge:tornado=6.1
  - tqdm=4.59.0
  - traitlets=5.0.5
  - bioconda:trimal=1.4.1
  - bioconda:trimmomatic=0.39
  - conda-forge:typing-extensions=3.7.4.3
  - conda-forge:typing_extensions=3.7.4.3
  - conda-forge:ubiquerg=0.6.1
  - bioconda:upimapi=1.1.4
  - conda-forge:uritemplate=3.0.1
  - conda-forge:urllib3=1.26.4
  - conda-forge:veracitools=0.1.3
  - conda-forge:wcwidth=0.2.5
  - conda-forge:wget=1.20.1
  - wheel=0.36.2
  - conda-forge:wrapt=1.12.1
  - conda-forge:xlrd=2.0.1
  - xlsxwriter=1.3.7
  - conda-forge:xmlrunner=1.7.7
  - conda-forge:xorg-fixesproto=5.0
  - conda-forge:xorg-inputproto=2.3.2
  - conda-forge:xorg-kbproto=1.0.7
  - conda-forge:xorg-libice=1.0.10
  - conda-forge:xorg-libsm=1.2.3
  - conda-forge:xorg-libx11=1.6.12
  - conda-forge:xorg-libxau=1.0.9
  - conda-forge:xorg-libxext=1.3.4
  - conda-forge:xorg-libxfixes=5.0.3
  - conda-forge:xorg-libxi=1.7.10
  - conda-forge:xorg-libxrender=0.9.10
  - conda-forge:xorg-libxt=1.2.1
  - conda-forge:xorg-libxtst=1.2.3
  - conda-forge:xorg-recordproto=1.14.2
  - conda-forge:xorg-renderproto=0.11.1
  - conda-forge:xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - conda-forge:xz=5.2.5
  - conda-forge:yaml=0.2.5
  - conda-forge:yarl=1.5.1
  - conda-forge:zipp=3.4.1
  - conda-forge:zlib=1.2.11
  - conda-forge:zstd=1.4.4
