name: CI

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile_CI
          tags: mosca:latest
          outputs: type=docker,dest=/tmp/mosca.tar

      - name: Create named volume
        run: docker volume create named_volume

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: mosca
          path: /tmp/mosca.tar

  use:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: mosca
          path: /tmp

      - name: Load Docker image
        run: |
          docker load --input /tmp/mosca.tar
          docker image ls -a

      - name: Check base entrypoint
        run: docker run mosca /bin/bash -c "ls"

      - name: Create named volume
        run: docker volume create named_volume

      - name: MGMT workflow
        run: docker run mosca /bin/bash -c "mosca.py -c MOSCARDO/configs/mgmt_config.json"

      - name: test_docker
        run: >
          docker run -v named_volume:/data -v /var/run/docker.sock:/var/run/docker.sock mosca /bin/bash 
          -c 'cp MOSCARDO/input/mp1/mp1.RAW data/mp1.RAW; docker run --rm -e WINEDEBUG=-all -v named_volume:/data chambm/pwiz-skyline-i-agree-to-the-vendor-licenses wine msconvert /data/mp1.RAW --mgf --filter "peakPicking cwt"; ls /data'

      - name: MGMP workflow
        run: >
          docker run -v named_volume:/data -v /var/run/docker.sock:/var/run/docker.sock mosca /bin/bash
          -c "mosca.py -c MOSCARDO/configs/mgmp_config.json; rm -r output"

      #- name: MG only workflow
      #  run: >
      #    docker run mosca /bin/bash -c "mkdir resources_directory; mv MOSCARDO/data/cdd.tar.gz resources_directory;
      #    cp MOSCARDO/data/mg_R1.fastq.gz MOSCARDO/data/mg_R1_001.fastq.gz;
      #    cp MOSCARDO/data/mg_R2.fastq.gz MOSCARDO/data/mg_R2_001.fastq.gz;
      #    mosca.py -c MOSCARDO/configs/mg_only_config.json"

      #- name: MT only workflow
      #  run: docker run mosca /bin/bash -c "mosca.py -c MOSCARDO/configs/mt_config.json"
