name: Continuous Integration

on:
  push:
    branches:
      - development
      - master        # master test only useful for badges
  pull_request:
    branches:
      - development
      - master        # master test only useful for badges

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile_CI
          tags: mosca:latest
          outputs: type=docker,dest=/tmp/mosca.tar
      - name: Create named volume
        run: docker volume create named_volume
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: mosca
          path: /tmp/mosca.tar

  mgmt-workflow:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: mosca
          path: /tmp
      - name: Load Docker image
        run: |
          docker load --input /tmp/mosca.tar
          docker image ls -a
      - name: MGMT workflow
        run: docker run mosca /bin/bash -c "mosca -c MOSCARDO/configs/mgmt_config.json"

  mgmp-workflow:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: mosca
          path: /tmp
      - name: Load Docker image
        run: |
          docker load --input /tmp/mosca.tar
          docker image ls -a
      - name: Create named volume
        run: docker volume create named_volume
      - name: MGMP workflow
        run: >
          docker run -v named_volume:/data -v /var/run/docker.sock:/var/run/docker.sock mosca /bin/bash
          -c "mosca -c MOSCARDO/configs/mgmp_config.json; du -sh output/*; df -h"
